disabled_rules:
- function_parameter_count
- multiple_closures_with_trailing_closure
- trailing_closure
opt_in_rules:
- empty_count
- empty_string
- multiline_parameters
- multiline_arguments_brackets
- multiline_parameters_brackets
excluded:
- Carthage
- SwiftLint/Common/3rdPartyLib
- "*.xcodeproj"
- ".git"
identifier_name:
  allowed_symbols:
    - _
  min_length: 1
  max_length: 40
  excluded:
    - Carthage
    - Pods
line_length:
    warning: 150
    error: 200
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
function_body_length:
    warning: 300
    error: 500
type_body_length:
    warning: 300
    error: 500
file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true
cyclomatic_complexity:
    warning: 15
    error: 25
reporter: "xcode"
